version: "3.6"

services:
  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch_springboot
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node 
      bootstrap.memory_lock: true 
      xpack.security.enabled: false 
    ports:
    - "9200:9200"
    networks:
      - elk

  Logstash:
    image: logstash:7.16.2
    container_name: logstash_springboot
    restart: always
    volumes:
    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - Elasticsearch
    ports:
    - "5044:5044"
    - "5000:5000/tcp"
    - "5000:5000/udp"
    - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    networks:
      - elk

  Kibana:
    image: kibana:7.16.2
    container_name: kibana_springboot
    restart: always       
    ports:
    - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"  
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - Elasticsearch  
    networks:
      - elk
volumes: 
   elastic_data:
        driver: local

networks:
  elk:
    driver: bridge